/*
*POR FAVOR CHAVALES EJECUTAR LAS TABLAS Y LAS COSAS UNA POR UNA 
*EXCEPTO LOS EXECUTE ESOS LOS PODEIS EJECUTAR POR BLOQUE LOS TENGO SEPARADOS 
*POR COMENTARIOS
*Y CUANDO LO HAGAIS BORRAIS ESTE MENSAJE DE MIERDA.
*/
DROP TABLE CLIENTES;
/*TABLA CLIENTE*/
CREATE TABLE CLIENTES (
	CIF VARCHAR2(10) NOT NULL UNIQUE,
	NOMBRE VARCHAR2(25)NOT NULL,
	DIRECCION VARCHAR2(50)NOT NULL,
	CORREOELECTRONICO VARCHAR2(75) NOT NULL UNIQUE,
	CONTRASEÑA VARCHAR2(75)NOT NULL ,
    TELEFONO   VARCHAR2(20)NOT NULL,
    ADMINISTRADOR VARCHAR(20) CHECK (ADMINISTRADOR IN ('YES','NO')),
	OID_CLI INTEGER NOT NULL,
	PRIMARY KEY (OID_CLI) 
);
/*SECUENCIA PARA INCREMENTAR AUTOMATICAMENTE EL OID_CLIENTE EN LA TABLA A LA HORA DE INTRODUCIR CON LA FUNCION INSERTAR CLIENTE*/
CREATE SEQUENCE SEC_CLIENTE_OID
START WITH 1 INCREMENT BY 1 NOMAXVALUE MINVALUE 1;
/*PROCEDIMIENTO PARA INSERTAR EL CLIENTE EN LA BASE DE DATOS, LA LLAMAMOS EN NUESTRO CODIGO PHP*/
create or replace PROCEDURE INSERTAR_CLIENTE
  (P_CIF IN CLIENTES.CIF%TYPE,
   P_NOMBRE IN CLIENTES.NOMBRE%TYPE,
   P_DIRECCION IN CLIENTES.DIRECCION%TYPE,
   P_CORREOELECTRONICO IN CLIENTES.CORREOELECTRONICO%TYPE,
   P_CONTRASEÑA IN CLIENTES.CONTRASEÑA%TYPE,
   P_TELCLIENTE IN CLIENTES.TELEFONO%TYPE
   ) IS
BEGIN
  INSERT INTO CLIENTES(CIF,NOMBRE,DIRECCION,CORREOELECTRONICO,CONTRASEÑA,TELEFONO,ADMINISTRADOR)
  VALUES (P_CIF,P_NOMBRE,P_DIRECCION,P_CORREOELECTRONICO,P_CONTRASEÑA,P_TELCLIENTE,'NO');
END;
/*CON ESTE TRIGGER INSERTAMOS EL SIGUIENTE OID QUE TOQUE EN LA SECUENCIA COMO NUEVO OID.CLI PARA EL USUARIO DE TURNO*/
create or replace TRIGGER INSERTAR_CLIENTE_OID
BEFORE INSERT ON CLIENTES
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
  SELECT SEC_CLIENTE_OID.NEXTVAL INTO :NEW.OID_CLI FROM DUAL;
END;
/*PROCEDIMIENTO PARA ACTUALIZAR EL CLIENTE EN LA BASE DE DATOS, LA LLAMAMOS EN NUESTRO CODIGO PHP*/
create or replace PROCEDURE ACTUALIZAR_CLIENTE
  (P_CIF IN CLIENTES.CIF%TYPE,
   P_NOMBRE IN CLIENTES.NOMBRE%TYPE,
   P_DIRECCION IN CLIENTES.DIRECCION%TYPE,
   P_CORREOELECTRONICO IN CLIENTES.CORREOELECTRONICO%TYPE,
   P_CONTRASEÑA IN CLIENTES.CONTRASEÑA%TYPE,
   P_TELCLIENTE IN CLIENTES.TELEFONO%TYPE
   ) IS
BEGIN
  UPDATE CLIENTES SET CIF=P_CIF, NOMBRE=P_NOMBRE, DIRECCION=P_DIRECCION, CORREOELECTRONICO=P_CORREOELECTRONICO, CONTRASEÑA=P_CONTRASEÑA, TELEFONO=P_TELCLIENTE 
  WHERE CORREOELECTRONICO = P_CORREOELECTRONICO;
END;

/*PROCEDIMIENTO PARA ACTUALIZAR PRODUCTOS*/
create or replace PROCEDURE ACTUALIZAR_PRODUCTO (
    P_IDENTIFICADOR IN PRODUCTOS.IDENTIFICADOR%TYPE,
    P_NOMBRE IN PRODUCTOS.NOMBRE%TYPE,
    P_DESCRIPCION IN PRODUCTOS.DESCRIPCION%TYPE,
    P_PRECIO IN PRODUCTOS.PRECIO%TYPE)
IS
BEGIN
UPDATE PRODUCTOS SET NOMBRE=P_NOMBRE, DESCRIPCION=P_DESCRIPCION, PRECIO=P_PRECIO
WHERE IDENTIFICADOR=P_IDENTIFICADOR;
END;
/*PROCEDIMIENTO PARA BORRAR EL CLIENTE EN LA BASE DE DATOS A PARTIR DE SU CORREO ELECTRONICO, LA LLAMAMOS EN NUESTRO CODIGO PHP*/
create or replace PROCEDURE BORRAR_CLIENTE
   (P_CORREOELECTRONICO IN CLIENTES.CORREOELECTRONICO%TYPE)
   IS
BEGIN
  DELETE CLIENTES WHERE CORREOELECTRONICO = P_CORREOELECTRONICO;
END;

/*IMPORTANTE INSERTAMOS EL USUARIO ADMIN A MANO PORQUE LOS USUARIOS QUE SE REGISTREN EN LA BASE DE DATOS SE REGISTRARAN DIRECTAMENTE COMO NO ADMINISTRADORES*/
insert into Clientes(CIF,NOMBRE,DIRECCION,CORREOELECTRONICO,CONTRASEÑA,TELEFONO,ADMINISTRADOR,OID_CLI) values('E89SD5423','Admin','c/Prueba','admin@admin.com','12345678g','631102599','YES',1);
/*A MODO DE PRUEBA DE QUE TODO FUNCIONA, INSERTAMOS CLIENTES EN LA BASE DATOS CON EL INSERTAR CLIENTE,*/ 
/*LOS ACTUALIZAMOS PONIENDOLE UN ESPACIO AL NOMBRE Y BORRAMOS EL CLIENTE 5 */
EXECUTE INSERTAR_CLIENTE('589665d55','Pymex','C/San Geronimo','cliente@cliente.com','12345678g','965221452');
EXECUTE INSERTAR_CLIENTE('589665d65','Cliente1','C/San Geronimo','cliente1@cliente.com','12345678g','965221452');
EXECUTE INSERTAR_CLIENTE('98589556d','Cliente2','C/San Francisco','cliente2@cliente.com','12345678g','924555652');
EXECUTE INSERTAR_CLIENTE('7457G445T','Cliente3','C/San Alcantara','cliente3@cliente.com','12345678g','924866548');
EXECUTE INSERTAR_CLIENTE('98DD562FS','Cliente4','Avnd.De la Paz s/n','cliente4@cliente.com','12345678g','924889556');
EXECUTE INSERTAR_CLIENTE('789DD54F2','Cliente5','C/Francisco De La Hera','cliente5@cliente.com','12345678g','924633255');
/*LOS ACTUALIZAMOS PONIENDOLE UN ESPACIO AL NOMBRE  */
EXECUTE ACTUALIZAR_CLIENTE('589665d65','Cliente 1','C/San Geronimo','cliente1@cliente.com','12345678g','965221452');
EXECUTE ACTUALIZAR_CLIENTE('98589556d','Cliente 2','C/San Francisco','cliente2@cliente.com','12345678g','924555652');
EXECUTE ACTUALIZAR_CLIENTE('7457G445T','Cliente 3','C/San Alcantara','cliente3@cliente.com','12345678g','924866548');
EXECUTE ACTUALIZAR_CLIENTE('98DD562FS','Cliente 4','Avnd.De la Paz s/n','cliente4@cliente.com','12345678g','924889556');
EXECUTE ACTUALIZAR_CLIENTE('789DD54F2','Cliente 5','C/Francisco De La Hera','cliente5@cliente.com','12345678g','924633255');
EXECUTE ACTUALIZAR_PRODUCTO('1','Redes Sociales','En etéreo nos comprometemos a que tu empresa tenga la mejor imagen de cara al público, sea reconocida y aumenten tus ventas. Todo ello de la mano de expertos community manager.',250);
EXECUTE ACTUALIZAR_PRODUCTO('2','Produccion','Una imagen vale más que mil palabra, una buena imagen tiene un valor incalculable. Etéreo te ofrece asesoramiento, creación y remasterización en todos los ámbitos del diseño.',550);

/*BORRAMOS EL CLIENTE 5*/
EXECUTE BORRAR_CLIENTE('cliente5@cliente.com');
/*VERIFICAMOS QUE SE HAN AÑADIDO NUESTROS DATOS*/
SELECT * FROM CLIENTES;
/*carrito*/
CREATE TABLE productos (
 identificador integer NOT NULL,
 nombre varchar2(200) NOT NULL,
 descripcion VARCHAR2(1000) NOT NULL,
 precio NUMBER NOT NULL,
 creado date NOT NULL,
 PRIMARY KEY (identificador)
)


CREATE SEQUENCE SEC_INSERTAR_PEDIDO_ID
START WITH 1 INCREMENT BY 1 NOMAXVALUE MINVALUE 1;    

CREATE TABLE PEDIDOS (
 identificador integer NOT NULL,
 cliente_id integer NOT NULL,
 precio_total float NOT NULL,
 creado date NOT NULL,
 PRIMARY KEY (identificador),
 FOREIGN KEY (cliente_id) REFERENCES CLIENTES(oid_cli) ON DELETE CASCADE 
); 

CREATE TABLE ProductosPedido (
    OID_P NUMBER NOT NULL,
    IdProducto NUMBER NOT NULL,
    Cantidad NUMBER NOT NULL,
    FOREIGN KEY(OID_P) REFERENCES Pedidos ON DELETE CASCADE
    );
/*TODOS LOS PRODUCTOS*/
INSERT INTO PRODUCTOS VALUES ('1','Redes Sociales',' En etéreo nos comprometemos a que tu empresa tenga la mejor imagen de cara al público, sea reconocida y aumenten tus ventas. 
Todo ello de la mano de expertos community manager.',250,TO_DATE('05/18/2019', 'MM/DD/YYYY'));
INSERT INTO PRODUCTOS VALUES ('2','Produccion Visual','Una imagen vale más que mil palabra, una buena imagen tiene un valor incalculable.
Etéreo te ofrece asesoramiento, creación y remasterización en todos los ámbitos del diseño.',500,TO_DATE('05/18/2019', 'MM/DD/YYYY'));
INSERT INTO PRODUCTOS VALUES ('3','Diseño Web','En Etéreo estamos especializados en la creación y desarrollo de páginas web, 
dándole a tu marca el valor añadido que merece tu negocio, transmitiendo tus valores de forma clara.',550,TO_DATE('05/18/2019', 'MM/DD/YYYY'));
INSERT INTO PRODUCTOS VALUES ('4','Fotografía','Contamos con fotógrafos profesionales, especializados tanto en foto catálogo, como en exteriores. 
Además de contar con una plantilla de productores profesionales que harán de tu vídeo promocional toda una delicia visual. ',150,TO_DATE('05/18/2019', 'MM/DD/YYYY'));
INSERT INTO PRODUCTOS VALUES ('5','Merchandasing','En Etéreo te ofrecemos la oportunidad de dar un paso más en tu empresa.
Creando así una línea corporativa tanto en material de empresa (bolígrafos, folios, carpetas...) como en uniformes de empresa.',200,TO_DATE('05/18/2019', 'MM/DD/YYYY'));
